version: '1'
services:
  stealth-tunnel:
    build:
      context: .
      dockerfile: Dockerfile.northflank
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
    resources:
      memory: 512MB
      cpu: 250m
