// GENERATED CODE -- DO NOT EDIT!

'use strict';

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tunnel.ClientType', null, global);
goog.exportSymbol('proto.tunnel.FrameType', null, global);
goog.exportSymbol('proto.tunnel.HttpRequest', null, global);
goog.exportSymbol('proto.tunnel.HttpResponse', null, global);
goog.exportSymbol('proto.tunnel.Registration', null, global);
goog.exportSymbol('proto.tunnel.RegistrationResponse', null, global);
goog.exportSymbol('proto.tunnel.TunnelFrame', null, global);
goog.exportSymbol('proto.tunnel.TunnelService', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty.
 * @param {number=} opt_ln Optional array length, used for initializing arrays
 * behind the scenes. The value should be a number.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnel.TunnelFrame = function(opt_data, opt_ln) {
  jspb.Message.initialize(this, opt_data, opt_ln, 0, -1, null, null);
};
goog.inherits(proto.tunnel.TunnelFrame, jspb.Message);
if (goog.DEBUG) {
  proto.tunnel.TunnelFrame.displayName = 'proto.tunnel.TunnelFrame';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object from the specified data.
 * @param {jspb.Message} msg The message.
 * @return {!Object}
 */
proto.tunnel.TunnelFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    frameId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    payload: msg.getPayload_asB64(),
    obfuscationMethod: jspb.Message.getFieldWithDefault(msg, 4, ""),
    maskType: jspb.Message.getFieldWithDefault(msg, 5, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 6, 0),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnel.TunnelFrame}
 */
proto.tunnel.TunnelFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnel.TunnelFrame;
  return proto.tunnel.TunnelFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnel.TunnelFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnel.TunnelFrame}
 */
proto.tunnel.TunnelFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrameId(value);
      break;
    case 2:
      var value = /** @type {!proto.tunnel.FrameType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPayload(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setObfuscationMethod(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaskType(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 7:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnel.TunnelFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnel.TunnelFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire format).
 * Writing to a BinaryWriter, the message's fields are written as
 * designated by the proto definition.
 * @param {!proto.tunnel.TunnelFrame} message The message to serialize.
 * @param {!jspb.BinaryWriter} writer The BinaryWriter to use.
 */
proto.tunnel.TunnelFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrameId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPayload_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getObfuscationMethod();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMaskType();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string frame_id = 1;
 * @return {string}
 */
proto.tunnel.TunnelFrame.prototype.getFrameId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setFrameId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional FrameType type = 2;
 * @return {!proto.tunnel.FrameType}
 */
proto.tunnel.TunnelFrame.prototype.getType = function() {
  return /** @type {!proto.tunnel.FrameType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.tunnel.FrameType} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional bytes payload = 3;
 * @return {!(string|Uint8Array)}
 */
proto.tunnel.TunnelFrame.prototype.getPayload = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes payload = 3;
 * This is a type-conversion wrapper around `getPayload()`
 * @return {string}
 */
proto.tunnel.TunnelFrame.prototype.getPayload_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPayload()));
};


/**
 * optional bytes payload = 3;
 * This is a type-conversion wrapper around `getPayload()`
 * @return {!Uint8Array}
 */
proto.tunnel.TunnelFrame.prototype.getPayload_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPayload()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setPayload = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string obfuscation_method = 4;
 * @return {string}
 */
proto.tunnel.TunnelFrame.prototype.getObfuscationMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setObfuscationMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string mask_type = 5;
 * @return {string}
 */
proto.tunnel.TunnelFrame.prototype.getMaskType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setMaskType = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 timestamp = 6;
 * @return {number}
 */
proto.tunnel.TunnelFrame.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * map<string, string> metadata = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 *     it doesn't already exist. Defaults to false.
 * @return {!jspb.Map<string,string>}
 */
proto.tunnel.TunnelFrame.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.tunnel.TunnelFrame} returns this
 */
proto.tunnel.TunnelFrame.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty.
 * @param {number=} opt_ln Optional array length, used for initializing arrays
 * behind the scenes. The value should be a number.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnel.HttpRequest = function(opt_data, opt_ln) {
  jspb.Message.initialize(this, opt_data, opt_ln, 0, -1, null, null);
};
goog.inherits(proto.tunnel.HttpRequest, jspb.Message);
if (goog.DEBUG) {
  proto.tunnel.HttpRequest.displayName = 'proto.tunnel.HttpRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object from the specified data.
 * @param {jspb.Message} msg The message.
 * @return {!Object}
 */
proto.tunnel.HttpRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    method: jspb.Message.getFieldWithDefault(msg, 2, ""),
    path: jspb.Message.getFieldWithDefault(msg, 3, ""),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, undefined) : [],
    body: msg.getBody_asB64(),
    queryMap: (f = msg.getQueryMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnel.HttpRequest}
 */
proto.tunnel.HttpRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnel.HttpRequest;
  return proto.tunnel.HttpRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnel.HttpRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnel.HttpRequest}
 */
proto.tunnel.HttpRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    case 6:
      var value = msg.getQueryMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnel.HttpRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnel.HttpRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire format).
 * Writing to a BinaryWriter, the message's fields are written as
 * designated by the proto definition.
 * @param {!proto.tunnel.HttpRequest} message The message to serialize.
 * @param {!jspb.BinaryWriter} writer The BinaryWriter to use.
 */
proto.tunnel.HttpRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getQueryMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.tunnel.HttpRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string method = 2;
 * @return {string}
 */
proto.tunnel.HttpRequest.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.tunnel.HttpRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, string> headers = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 *     it doesn't already exist. Defaults to false.
 * @return {!jspb.Map<string,string>}
 */
proto.tunnel.HttpRequest.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;
};


/**
 * optional bytes body = 5;
 * @return {!(string|Uint8Array)}
 */
proto.tunnel.HttpRequest.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes body = 5;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.tunnel.HttpRequest.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 5;
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.tunnel.HttpRequest.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.setBody = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * map<string, string> query = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 *     it doesn't already exist. Defaults to false.
 * @return {!jspb.Map<string,string>}
 */
proto.tunnel.HttpRequest.prototype.getQueryMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.tunnel.HttpRequest} returns this
 */
proto.tunnel.HttpRequest.prototype.clearQueryMap = function() {
  this.getQueryMap().clear();
  return this;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty.
 * @param {number=} opt_ln Optional array length, used for initializing arrays
 * behind the scenes. The value should be a number.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnel.HttpResponse = function(opt_data, opt_ln) {
  jspb.Message.initialize(this, opt_data, opt_ln, 0, -1, null, null);
};
goog.inherits(proto.tunnel.HttpResponse, jspb.Message);
if (goog.DEBUG) {
  proto.tunnel.HttpResponse.displayName = 'proto.tunnel.HttpResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object from the specified data.
 * @param {jspb.Message} msg The message.
 * @return {!Object}
 */
proto.tunnel.HttpResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, undefined) : [],
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnel.HttpResponse}
 */
proto.tunnel.HttpResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnel.HttpResponse;
  return proto.tunnel.HttpResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnel.HttpResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnel.HttpResponse}
 */
proto.tunnel.HttpResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 3:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnel.HttpResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnel.HttpResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire format).
 * Writing to a BinaryWriter, the message's fields are written as
 * designated by the proto definition.
 * @param {!proto.tunnel.HttpResponse} message The message to serialize.
 * @param {!jspb.BinaryWriter} writer The BinaryWriter to use.
 */
proto.tunnel.HttpResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.tunnel.HttpResponse.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.HttpResponse} returns this
 */
proto.tunnel.HttpResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 status = 2;
 * @return {number}
 */
proto.tunnel.HttpResponse.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tunnel.HttpResponse} returns this
 */
proto.tunnel.HttpResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * map<string, string> headers = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 *     it doesn't already exist. Defaults to false.
 * @return {!jspb.Map<string,string>}
 */
proto.tunnel.HttpResponse.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.tunnel.HttpResponse} returns this
 */
proto.tunnel.HttpResponse.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;
};


/**
 * optional bytes body = 4;
 * @return {!(string|Uint8Array)}
 */
proto.tunnel.HttpResponse.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes body = 4;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.tunnel.HttpResponse.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 4;
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.tunnel.HttpResponse.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.tunnel.HttpResponse} returns this
 */
proto.tunnel.HttpResponse.prototype.setBody = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty.
 * @param {number=} opt_ln Optional array length, used for initializing arrays
 * behind the scenes. The value should be a number.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnel.Registration = function(opt_data, opt_ln) {
  jspb.Message.initialize(this, opt_data, opt_ln, 0, -1, proto.tunnel.Registration.repeatedFields_, null);
};
goog.inherits(proto.tunnel.Registration, jspb.Message);
if (goog.DEBUG) {
  proto.tunnel.Registration.displayName = 'proto.tunnel.Registration';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tunnel.Registration.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object from the specified data.
 * @param {jspb.Message} msg The message.
 * @return {!Object}
 */
proto.tunnel.Registration.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clientType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    capabilitiesList: jspb.Message.getRepeatedField(msg, 3),
    localAppUrl: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnel.Registration}
 */
proto.tunnel.Registration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnel.Registration;
  return proto.tunnel.Registration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnel.Registration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnel.Registration}
 */
proto.tunnel.Registration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {!proto.tunnel.ClientType} */ (reader.readEnum());
      msg.setClientType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addCapabilities(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalAppUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnel.Registration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnel.Registration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire format).
 * Writing to a BinaryWriter, the message's fields are written as
 * designated by the proto definition.
 * @param {!proto.tunnel.Registration} message The message to serialize.
 * @param {!jspb.BinaryWriter} writer The BinaryWriter to use.
 */
proto.tunnel.Registration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClientType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCapabilitiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getLocalAppUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.tunnel.Registration.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.setClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ClientType client_type = 2;
 * @return {!proto.tunnel.ClientType}
 */
proto.tunnel.Registration.prototype.getClientType = function() {
  return /** @type {!proto.tunnel.ClientType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.tunnel.ClientType} value
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.setClientType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated string capabilities = 3;
 * @return {!Array<string>}
 */
proto.tunnel.Registration.prototype.getCapabilitiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.setCapabilitiesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.addCapabilities = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.clearCapabilitiesList = function() {
  return this.setCapabilitiesList([]);
};


/**
 * optional string local_app_url = 4;
 * @return {string}
 */
proto.tunnel.Registration.prototype.getLocalAppUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.Registration} returns this
 */
proto.tunnel.Registration.prototype.setLocalAppUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty.
 * @param {number=} opt_ln Optional array length, used for initializing arrays
 * behind the scenes. The value should be a number.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tunnel.RegistrationResponse = function(opt_data, opt_ln) {
  jspb.Message.initialize(this, opt_data, opt_ln, 0, -1, null, null);
};
goog.inherits(proto.tunnel.RegistrationResponse, jspb.Message);
if (goog.DEBUG) {
  proto.tunnel.RegistrationResponse.displayName = 'proto.tunnel.RegistrationResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object from the specified data.
 * @param {jspb.Message} msg The message.
 * @return {!Object}
 */
proto.tunnel.RegistrationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tunnelId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    serverVersion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    obfuscationMethod: jspb.Message.getFieldWithDefault(msg, 4, ""),
    serverTime: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tunnel.RegistrationResponse}
 */
proto.tunnel.RegistrationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tunnel.RegistrationResponse;
  return proto.tunnel.RegistrationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tunnel.RegistrationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tunnel.RegistrationResponse}
 */
proto.tunnel.RegistrationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTunnelId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerVersion(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setObfuscationMethod(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setServerTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tunnel.RegistrationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tunnel.RegistrationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire format).
 * Writing to a BinaryWriter, the message's fields are written as
 * designated by the proto definition.
 * @param {!proto.tunnel.RegistrationResponse} message The message to serialize.
 * @param {!jspb.BinaryWriter} writer The BinaryWriter to use.
 */
proto.tunnel.RegistrationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTunnelId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getServerVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getObfuscationMethod();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getServerTime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.tunnel.RegistrationResponse.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.RegistrationResponse} returns this
 */
proto.tunnel.RegistrationResponse.prototype.setClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string tunnel_id = 2;
 * @return {string}
 */
proto.tunnel.RegistrationResponse.prototype.getTunnelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.RegistrationResponse} returns this
 */
proto.tunnel.RegistrationResponse.prototype.setTunnelId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string server_version = 3;
 * @return {string}
 */
proto.tunnel.RegistrationResponse.prototype.getServerVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.RegistrationResponse} returns this
 */
proto.tunnel.RegistrationResponse.prototype.setServerVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string obfuscation_method = 4;
 * @return {string}
 */
proto.tunnel.RegistrationResponse.prototype.getObfuscationMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tunnel.RegistrationResponse} returns this
 */
proto.tunnel.RegistrationResponse.prototype.setObfuscationMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 server_time = 5;
 * @return {number}
 */
proto.tunnel.RegistrationResponse.prototype.getServerTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.tunnel.RegistrationResponse} returns this
 */
proto.tunnel.RegistrationResponse.prototype.setServerTime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.tunnel.FrameType = {
  REGISTER: 0,
  HTTP_REQUEST: 1,
  HTTP_RESPONSE: 2,
  HEALTH_CHECK: 3,
  PING: 4,
  PONG: 5,
  DATA: 6,
  ERROR: 7
};

/**
 * @enum {number}
 */
proto.tunnel.ClientType = {
  LAPTOP: 0,
  BROWSER: 1
};

/**
 * A TensorFlowServiceClient.
 * @param {!string} hostname
 * @param {?Object} credentials
 * @param {?Object} options
 * @constructor
 * @struct
 * @final
 */
proto.tunnel.TunnelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options['format'] = 'text';

  /**
   * @private @const {!grpc.web.AbstractClientBase} The client
   */
  this.client_ = new grpc.web.AbstractClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname;

  /**
   * @private @const {?Object} The credentials to be used to connect
   */
  this.credentials_ = credentials;

  /**
   * @private @const {?Object} Options for the client
   */
  this.options_ = options;
};


/**
 * @param {!string} hostname
 * @param {?Object} credentials
 * @param {?Object} options
 * @return {!proto.tunnel.TunnelServiceClient}
 * @static
 */
proto.tunnel.TunnelServiceClient.createClient =
    function(hostname, credentials, options) {
  return new proto.tunnel.TunnelServiceClient(hostname, credentials, options);
};


/**
 * @const
 * @type {!grpc.web.AbstractClientBase.MethodInfo<
 *   !proto.tunnel.TunnelFrame,
 *   !proto.tunnel.TunnelFrame>}
 */
const methodInfo_TunnelService_TunnelStream = new grpc.web.AbstractClientBase.MethodInfo(
  proto.tunnel.TunnelFrame,
  /** @param {!proto.tunnel.TunnelFrame} request */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.TunnelFrame.deserializeBinary
);


/**
 * @param {!proto.tunnel.TunnelFrame} request The request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.TunnelFrame>}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.tunnelStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/tunnel.TunnelService/TunnelStream',
      request,
      metadata || {},
      methodInfo_TunnelService_TunnelStream);
};


/**
 * @const
 * @type {!grpc.web.AbstractClientBase.MethodInfo<
 *   !proto.tunnel.HttpRequest,
 *   !proto.tunnel.HttpResponse>}
 */
const methodInfo_TunnelService_HttpProxy = new grpc.web.AbstractClientBase.MethodInfo(
  proto.tunnel.HttpResponse,
  /** @param {!proto.tunnel.HttpRequest} request */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.HttpResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.HttpRequest} request The request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.HttpResponse>}
 *     A native promise that resolves to the response
 */
proto.tunnel.TunnelServiceClient.prototype.httpProxy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/HttpProxy',
      request,
      metadata || {},
      methodInfo_TunnelService_HttpProxy);
};


/**
 * @const
 * @type {!grpc.web.AbstractClientBase.MethodInfo<
 *   !proto.tunnel.Registration,
 *   !proto.tunnel.RegistrationResponse>}
 */
const methodInfo_TunnelService_Register = new grpc.web.AbstractClientBase.MethodInfo(
  proto.tunnel.RegistrationResponse,
  /** @param {!proto.tunnel.Registration} request */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.RegistrationResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.Registration} request The request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.RegistrationResponse>}
 *     A native promise that resolves to the response
 */
proto.tunnel.TunnelServiceClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/Register',
      request,
      metadata || {},
      methodInfo_TunnelService_Register);
};


/**
 * @const
 * @type {!grpc.web.AbstractClientBase.MethodInfo<
 *   !proto.tunnel.TunnelFrame,
 *   !proto.tunnel.TunnelFrame>}
 */
const methodInfo_TunnelService_TunnelStream = new grpc.web.AbstractClientBase.MethodInfo(
  proto.tunnel.TunnelFrame,
  /** @param {!proto.tunnel.TunnelFrame} request */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.TunnelFrame.deserializeBinary
);


/**
 * @param {!proto.tunnel.TunnelFrame} request The request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.TunnelFrame>}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.tunnelStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/tunnel.TunnelService/TunnelStream',
      request,
      metadata || {},
      methodInfo_TunnelService_TunnelStream);
};


module.exports = proto.tunnel;
