/**
 * @fileoverview gRPC-Web generated client stub for tunnel
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: proto/tunnel.proto


/* eslint-disable */
// @ts-nocheck


var grpc = require('./grpc-web-adapter.cjs');
const proto = {};
proto.tunnel = require('./proto/tunnel_pb.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tunnel.TunnelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tunnel.TunnelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.HttpRequest,
 *   !proto.tunnel.HttpResponse>}
 */
const methodDescriptor_TunnelService_HttpProxy = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/HttpProxy',
  grpc.web.MethodType.UNARY,
  proto.tunnel.HttpRequest,
  proto.tunnel.HttpResponse,
  /**
   * @param {!proto.tunnel.HttpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.HttpResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.HttpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.HttpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.HttpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.httpProxy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/HttpProxy',
      request,
      metadata || {},
      methodDescriptor_TunnelService_HttpProxy,
      callback);
};


/**
 * @param {!proto.tunnel.HttpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.HttpResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.httpProxy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/HttpProxy',
      request,
      metadata || {},
      methodDescriptor_TunnelService_HttpProxy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.RegistrationRequest,
 *   !proto.tunnel.RegistrationResponse>}
 */
const methodDescriptor_TunnelService_Register = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/Register',
  grpc.web.MethodType.UNARY,
  proto.tunnel.RegistrationRequest,
  proto.tunnel.RegistrationResponse,
  /**
   * @param {!proto.tunnel.RegistrationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.RegistrationResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.RegistrationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.RegistrationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/Register',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Register,
      callback);
};


/**
 * @param {!proto.tunnel.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.RegistrationResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/Register',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.HealthCheck,
 *   !proto.tunnel.HealthResponse>}
 */
const methodDescriptor_TunnelService_CheckHealth = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/CheckHealth',
  grpc.web.MethodType.UNARY,
  proto.tunnel.HealthCheck,
  proto.tunnel.HealthResponse,
  /**
   * @param {!proto.tunnel.HealthCheck} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.HealthResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.HealthCheck} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.HealthResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.HealthResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.checkHealth =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/CheckHealth',
      request,
      metadata || {},
      methodDescriptor_TunnelService_CheckHealth,
      callback);
};


/**
 * @param {!proto.tunnel.HealthCheck} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.HealthResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.checkHealth =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/CheckHealth',
      request,
      metadata || {},
      methodDescriptor_TunnelService_CheckHealth);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.StatsRequest,
 *   !proto.tunnel.Stats>}
 */
const methodDescriptor_TunnelService_GetStats = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/GetStats',
  grpc.web.MethodType.UNARY,
  proto.tunnel.StatsRequest,
  proto.tunnel.Stats,
  /**
   * @param {!proto.tunnel.StatsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.Stats.deserializeBinary
);


/**
 * @param {!proto.tunnel.StatsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.Stats)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.Stats>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.getStats =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/GetStats',
      request,
      metadata || {},
      methodDescriptor_TunnelService_GetStats,
      callback);
};


/**
 * @param {!proto.tunnel.StatsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.Stats>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.getStats =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/GetStats',
      request,
      metadata || {},
      methodDescriptor_TunnelService_GetStats);
};


module.exports = proto.tunnel;

