/**
 * @fileoverview gRPC-Web generated client stub for tunnel
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: proto/tunnel.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.tunnel = require('./tunnel_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tunnel.TunnelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.tunnel.TunnelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.RegistrationRequest,
 *   !proto.tunnel.RegistrationResponse>}
 */
const methodDescriptor_TunnelService_Register = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/Register',
  grpc.web.MethodType.UNARY,
  proto.tunnel.RegistrationRequest,
  proto.tunnel.RegistrationResponse,
  /**
   * @param {!proto.tunnel.RegistrationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.RegistrationResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.RegistrationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.RegistrationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/Register',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Register,
      callback);
};


/**
 * @param {!proto.tunnel.RegistrationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.RegistrationResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/Register',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.HealthCheckMsg,
 *   !proto.tunnel.HealthResponseMsg>}
 */
const methodDescriptor_TunnelService_HealthCheck = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/HealthCheck',
  grpc.web.MethodType.UNARY,
  proto.tunnel.HealthCheckMsg,
  proto.tunnel.HealthResponseMsg,
  /**
   * @param {!proto.tunnel.HealthCheckMsg} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.HealthResponseMsg.deserializeBinary
);


/**
 * @param {!proto.tunnel.HealthCheckMsg} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.HealthResponseMsg)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.HealthResponseMsg>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.healthCheck =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/HealthCheck',
      request,
      metadata || {},
      methodDescriptor_TunnelService_HealthCheck,
      callback);
};


/**
 * @param {!proto.tunnel.HealthCheckMsg} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.HealthResponseMsg>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.healthCheck =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/HealthCheck',
      request,
      metadata || {},
      methodDescriptor_TunnelService_HealthCheck);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.SendFrameRequest,
 *   !proto.tunnel.SendFrameResponse>}
 */
const methodDescriptor_TunnelService_SendFrame = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/SendFrame',
  grpc.web.MethodType.UNARY,
  proto.tunnel.SendFrameRequest,
  proto.tunnel.SendFrameResponse,
  /**
   * @param {!proto.tunnel.SendFrameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.SendFrameResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.SendFrameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.SendFrameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.SendFrameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.sendFrame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/SendFrame',
      request,
      metadata || {},
      methodDescriptor_TunnelService_SendFrame,
      callback);
};


/**
 * @param {!proto.tunnel.SendFrameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.SendFrameResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.sendFrame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/SendFrame',
      request,
      metadata || {},
      methodDescriptor_TunnelService_SendFrame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.PollRequest,
 *   !proto.tunnel.PollResponse>}
 */
const methodDescriptor_TunnelService_PollFrames = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/PollFrames',
  grpc.web.MethodType.UNARY,
  proto.tunnel.PollRequest,
  proto.tunnel.PollResponse,
  /**
   * @param {!proto.tunnel.PollRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.PollResponse.deserializeBinary
);


/**
 * @param {!proto.tunnel.PollRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.PollResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.PollResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.pollFrames =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/PollFrames',
      request,
      metadata || {},
      methodDescriptor_TunnelService_PollFrames,
      callback);
};


/**
 * @param {!proto.tunnel.PollRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.PollResponse>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.pollFrames =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/PollFrames',
      request,
      metadata || {},
      methodDescriptor_TunnelService_PollFrames);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.tunnel.HealthCheckMsg,
 *   !proto.tunnel.HealthResponseMsg>}
 */
const methodDescriptor_TunnelService_KeepAlive = new grpc.web.MethodDescriptor(
  '/tunnel.TunnelService/KeepAlive',
  grpc.web.MethodType.UNARY,
  proto.tunnel.HealthCheckMsg,
  proto.tunnel.HealthResponseMsg,
  /**
   * @param {!proto.tunnel.HealthCheckMsg} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.tunnel.HealthResponseMsg.deserializeBinary
);


/**
 * @param {!proto.tunnel.HealthCheckMsg} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.tunnel.HealthResponseMsg)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.tunnel.HealthResponseMsg>|undefined}
 *     The XHR Node Readable Stream
 */
proto.tunnel.TunnelServiceClient.prototype.keepAlive =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/tunnel.TunnelService/KeepAlive',
      request,
      metadata || {},
      methodDescriptor_TunnelService_KeepAlive,
      callback);
};


/**
 * @param {!proto.tunnel.HealthCheckMsg} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.tunnel.HealthResponseMsg>}
 *     Promise that resolves to the response
 */
proto.tunnel.TunnelServicePromiseClient.prototype.keepAlive =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/tunnel.TunnelService/KeepAlive',
      request,
      metadata || {},
      methodDescriptor_TunnelService_KeepAlive);
};


module.exports = proto.tunnel;

